// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public final class ForgeDriverProto {
  private ForgeDriverProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_TapRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_TapRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_TapByTextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_TapByTextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_TapByCoordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_TapByCoordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_TypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_TypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_SwipeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_SwipeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_PressKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_PressKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_WaitPresentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_WaitPresentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_IsPresentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_IsPresentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_SourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_SourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_ScreenshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_ScreenshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_ActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_ActionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_WaitPresentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_WaitPresentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_IsPresentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_IsPresentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_SourceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_SourceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forgedriver_ScreenshotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forgedriver_ScreenshotResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022forge_driver.proto\022\013forgedriver\"\r\n\013Pin" +
      "gRequest\"\036\n\014PingResponse\022\016\n\006status\030\001 \001(\t" +
      "\"\031\n\nTapRequest\022\013\n\003tag\030\001 \001(\t\" \n\020TapByText" +
      "Request\022\014\n\004text\030\001 \001(\t\"*\n\022TapByCoordsRequ" +
      "est\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\"\033\n\013TypeRequest" +
      "\022\014\n\004text\030\001 \001(\t\"Q\n\014SwipeRequest\022\021\n\tdirect" +
      "ion\030\001 \001(\t\022\n\n\002x1\030\002 \001(\005\022\n\n\002y1\030\003 \001(\005\022\n\n\002x2\030" +
      "\004 \001(\005\022\n\n\002y2\030\005 \001(\005\"\036\n\017PressKeyRequest\022\013\n\003" +
      "key\030\001 \001(\t\"5\n\022WaitPresentRequest\022\013\n\003tag\030\001" +
      " \001(\t\022\022\n\ntimeout_ms\030\002 \001(\003\"\037\n\020IsPresentReq" +
      "uest\022\013\n\003tag\030\001 \001(\t\"\017\n\rSourceRequest\"\023\n\021Sc" +
      "reenshotRequest\"0\n\016ActionResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\"^\n\023WaitPresent" +
      "Response\022\r\n\005found\030\001 \001(\010\022\014\n\004left\030\002 \001(\005\022\013\n" +
      "\003top\030\003 \001(\005\022\r\n\005right\030\004 \001(\005\022\016\n\006bottom\030\005 \001(" +
      "\005\"\"\n\021IsPresentResponse\022\r\n\005found\030\001 \001(\010\"\035\n" +
      "\016SourceResponse\022\013\n\003xml\030\001 \001(\t\"!\n\022Screensh" +
      "otResponse\022\013\n\003png\030\001 \001(\0142\336\006\n\013ForgeDriver\022" +
      ";\n\004Ping\022\030.forgedriver.PingRequest\032\031.forg" +
      "edriver.PingResponse\022;\n\003Tap\022\027.forgedrive" +
      "r.TapRequest\032\033.forgedriver.ActionRespons" +
      "e\022G\n\tTapByText\022\035.forgedriver.TapByTextRe" +
      "quest\032\033.forgedriver.ActionResponse\022K\n\013Ta" +
      "pByCoords\022\037.forgedriver.TapByCoordsReque" +
      "st\032\033.forgedriver.ActionResponse\022=\n\004Type\022" +
      "\030.forgedriver.TypeRequest\032\033.forgedriver." +
      "ActionResponse\022E\n\014ClearAndType\022\030.forgedr" +
      "iver.TypeRequest\032\033.forgedriver.ActionRes" +
      "ponse\022?\n\005Swipe\022\031.forgedriver.SwipeReques" +
      "t\032\033.forgedriver.ActionResponse\022E\n\010PressK" +
      "ey\022\034.forgedriver.PressKeyRequest\032\033.forge" +
      "driver.ActionResponse\022P\n\013WaitPresent\022\037.f" +
      "orgedriver.WaitPresentRequest\032 .forgedri" +
      "ver.WaitPresentResponse\022J\n\tIsPresent\022\035.f" +
      "orgedriver.IsPresentRequest\032\036.forgedrive" +
      "r.IsPresentResponse\022D\n\tGetSource\022\032.forge" +
      "driver.SourceRequest\032\033.forgedriver.Sourc" +
      "eResponse\022M\n\nScreenshot\022\036.forgedriver.Sc" +
      "reenshotRequest\032\037.forgedriver.Screenshot" +
      "ResponseB3\n\035com.popclub.forgedriver.prot" +
      "oB\020ForgeDriverProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_forgedriver_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forgedriver_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_PingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_forgedriver_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_forgedriver_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_PingResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_forgedriver_TapRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_forgedriver_TapRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_TapRequest_descriptor,
        new java.lang.String[] { "Tag", });
    internal_static_forgedriver_TapByTextRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_forgedriver_TapByTextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_TapByTextRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_forgedriver_TapByCoordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_forgedriver_TapByCoordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_TapByCoordsRequest_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_forgedriver_TypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_forgedriver_TypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_TypeRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_forgedriver_SwipeRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_forgedriver_SwipeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_SwipeRequest_descriptor,
        new java.lang.String[] { "Direction", "X1", "Y1", "X2", "Y2", });
    internal_static_forgedriver_PressKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_forgedriver_PressKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_PressKeyRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_forgedriver_WaitPresentRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_forgedriver_WaitPresentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_WaitPresentRequest_descriptor,
        new java.lang.String[] { "Tag", "TimeoutMs", });
    internal_static_forgedriver_IsPresentRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_forgedriver_IsPresentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_IsPresentRequest_descriptor,
        new java.lang.String[] { "Tag", });
    internal_static_forgedriver_SourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_forgedriver_SourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_SourceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_forgedriver_ScreenshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_forgedriver_ScreenshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_ScreenshotRequest_descriptor,
        new java.lang.String[] { });
    internal_static_forgedriver_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_forgedriver_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_ActionResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_forgedriver_WaitPresentResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_forgedriver_WaitPresentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_WaitPresentResponse_descriptor,
        new java.lang.String[] { "Found", "Left", "Top", "Right", "Bottom", });
    internal_static_forgedriver_IsPresentResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_forgedriver_IsPresentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_IsPresentResponse_descriptor,
        new java.lang.String[] { "Found", });
    internal_static_forgedriver_SourceResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_forgedriver_SourceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_SourceResponse_descriptor,
        new java.lang.String[] { "Xml", });
    internal_static_forgedriver_ScreenshotResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_forgedriver_ScreenshotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forgedriver_ScreenshotResponse_descriptor,
        new java.lang.String[] { "Png", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
