// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface IsPresentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.IsPresentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  boolean getFound();
}
