// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.PingRequest)
    com.google.protobuf.MessageOrBuilder {
}
