// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface ScreenshotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.ScreenshotRequest)
    com.google.protobuf.MessageOrBuilder {
}
