// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface ScreenshotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.ScreenshotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes png = 1;</code>
   * @return The png.
   */
  com.google.protobuf.ByteString getPng();
}
