// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

/**
 * Protobuf type {@code forgedriver.ScreenshotResponse}
 */
public final class ScreenshotResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:forgedriver.ScreenshotResponse)
    ScreenshotResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScreenshotResponse.newBuilder() to construct.
  private ScreenshotResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScreenshotResponse() {
    png_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScreenshotResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_ScreenshotResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_ScreenshotResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.popclub.forgedriver.proto.ScreenshotResponse.class, com.popclub.forgedriver.proto.ScreenshotResponse.Builder.class);
  }

  public static final int PNG_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString png_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes png = 1;</code>
   * @return The png.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPng() {
    return png_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!png_.isEmpty()) {
      output.writeBytes(1, png_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!png_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, png_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.popclub.forgedriver.proto.ScreenshotResponse)) {
      return super.equals(obj);
    }
    com.popclub.forgedriver.proto.ScreenshotResponse other = (com.popclub.forgedriver.proto.ScreenshotResponse) obj;

    if (!getPng()
        .equals(other.getPng())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PNG_FIELD_NUMBER;
    hash = (53 * hash) + getPng().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.popclub.forgedriver.proto.ScreenshotResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.popclub.forgedriver.proto.ScreenshotResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.ScreenshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.popclub.forgedriver.proto.ScreenshotResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code forgedriver.ScreenshotResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:forgedriver.ScreenshotResponse)
      com.popclub.forgedriver.proto.ScreenshotResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_ScreenshotResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_ScreenshotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.popclub.forgedriver.proto.ScreenshotResponse.class, com.popclub.forgedriver.proto.ScreenshotResponse.Builder.class);
    }

    // Construct using com.popclub.forgedriver.proto.ScreenshotResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      png_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_ScreenshotResponse_descriptor;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.ScreenshotResponse getDefaultInstanceForType() {
      return com.popclub.forgedriver.proto.ScreenshotResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.ScreenshotResponse build() {
      com.popclub.forgedriver.proto.ScreenshotResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.ScreenshotResponse buildPartial() {
      com.popclub.forgedriver.proto.ScreenshotResponse result = new com.popclub.forgedriver.proto.ScreenshotResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.popclub.forgedriver.proto.ScreenshotResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.png_ = png_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.popclub.forgedriver.proto.ScreenshotResponse) {
        return mergeFrom((com.popclub.forgedriver.proto.ScreenshotResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.popclub.forgedriver.proto.ScreenshotResponse other) {
      if (other == com.popclub.forgedriver.proto.ScreenshotResponse.getDefaultInstance()) return this;
      if (other.getPng() != com.google.protobuf.ByteString.EMPTY) {
        setPng(other.getPng());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              png_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString png_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes png = 1;</code>
     * @return The png.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPng() {
      return png_;
    }
    /**
     * <code>bytes png = 1;</code>
     * @param value The png to set.
     * @return This builder for chaining.
     */
    public Builder setPng(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      png_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes png = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPng() {
      bitField0_ = (bitField0_ & ~0x00000001);
      png_ = getDefaultInstance().getPng();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:forgedriver.ScreenshotResponse)
  }

  // @@protoc_insertion_point(class_scope:forgedriver.ScreenshotResponse)
  private static final com.popclub.forgedriver.proto.ScreenshotResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.popclub.forgedriver.proto.ScreenshotResponse();
  }

  public static com.popclub.forgedriver.proto.ScreenshotResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScreenshotResponse>
      PARSER = new com.google.protobuf.AbstractParser<ScreenshotResponse>() {
    @java.lang.Override
    public ScreenshotResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScreenshotResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScreenshotResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.popclub.forgedriver.proto.ScreenshotResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

