// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface SourceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.SourceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string xml = 1;</code>
   * @return The xml.
   */
  java.lang.String getXml();
  /**
   * <code>string xml = 1;</code>
   * @return The bytes for xml.
   */
  com.google.protobuf.ByteString
      getXmlBytes();
}
