// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface SwipeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.SwipeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string direction = 1;</code>
   * @return The direction.
   */
  java.lang.String getDirection();
  /**
   * <code>string direction = 1;</code>
   * @return The bytes for direction.
   */
  com.google.protobuf.ByteString
      getDirectionBytes();

  /**
   * <code>int32 x1 = 2;</code>
   * @return The x1.
   */
  int getX1();

  /**
   * <code>int32 y1 = 3;</code>
   * @return The y1.
   */
  int getY1();

  /**
   * <code>int32 x2 = 4;</code>
   * @return The x2.
   */
  int getX2();

  /**
   * <code>int32 y2 = 5;</code>
   * @return The y2.
   */
  int getY2();
}
