// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

/**
 * Protobuf type {@code forgedriver.SwipeRequest}
 */
public final class SwipeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:forgedriver.SwipeRequest)
    SwipeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SwipeRequest.newBuilder() to construct.
  private SwipeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SwipeRequest() {
    direction_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SwipeRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_SwipeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_SwipeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.popclub.forgedriver.proto.SwipeRequest.class, com.popclub.forgedriver.proto.SwipeRequest.Builder.class);
  }

  public static final int DIRECTION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object direction_ = "";
  /**
   * <code>string direction = 1;</code>
   * @return The direction.
   */
  @java.lang.Override
  public java.lang.String getDirection() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      direction_ = s;
      return s;
    }
  }
  /**
   * <code>string direction = 1;</code>
   * @return The bytes for direction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDirectionBytes() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      direction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X1_FIELD_NUMBER = 2;
  private int x1_ = 0;
  /**
   * <code>int32 x1 = 2;</code>
   * @return The x1.
   */
  @java.lang.Override
  public int getX1() {
    return x1_;
  }

  public static final int Y1_FIELD_NUMBER = 3;
  private int y1_ = 0;
  /**
   * <code>int32 y1 = 3;</code>
   * @return The y1.
   */
  @java.lang.Override
  public int getY1() {
    return y1_;
  }

  public static final int X2_FIELD_NUMBER = 4;
  private int x2_ = 0;
  /**
   * <code>int32 x2 = 4;</code>
   * @return The x2.
   */
  @java.lang.Override
  public int getX2() {
    return x2_;
  }

  public static final int Y2_FIELD_NUMBER = 5;
  private int y2_ = 0;
  /**
   * <code>int32 y2 = 5;</code>
   * @return The y2.
   */
  @java.lang.Override
  public int getY2() {
    return y2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, direction_);
    }
    if (x1_ != 0) {
      output.writeInt32(2, x1_);
    }
    if (y1_ != 0) {
      output.writeInt32(3, y1_);
    }
    if (x2_ != 0) {
      output.writeInt32(4, x2_);
    }
    if (y2_ != 0) {
      output.writeInt32(5, y2_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, direction_);
    }
    if (x1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, x1_);
    }
    if (y1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, y1_);
    }
    if (x2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, x2_);
    }
    if (y2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, y2_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.popclub.forgedriver.proto.SwipeRequest)) {
      return super.equals(obj);
    }
    com.popclub.forgedriver.proto.SwipeRequest other = (com.popclub.forgedriver.proto.SwipeRequest) obj;

    if (!getDirection()
        .equals(other.getDirection())) return false;
    if (getX1()
        != other.getX1()) return false;
    if (getY1()
        != other.getY1()) return false;
    if (getX2()
        != other.getX2()) return false;
    if (getY2()
        != other.getY2()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection().hashCode();
    hash = (37 * hash) + X1_FIELD_NUMBER;
    hash = (53 * hash) + getX1();
    hash = (37 * hash) + Y1_FIELD_NUMBER;
    hash = (53 * hash) + getY1();
    hash = (37 * hash) + X2_FIELD_NUMBER;
    hash = (53 * hash) + getX2();
    hash = (37 * hash) + Y2_FIELD_NUMBER;
    hash = (53 * hash) + getY2();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.popclub.forgedriver.proto.SwipeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.popclub.forgedriver.proto.SwipeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.SwipeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.popclub.forgedriver.proto.SwipeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code forgedriver.SwipeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:forgedriver.SwipeRequest)
      com.popclub.forgedriver.proto.SwipeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_SwipeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_SwipeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.popclub.forgedriver.proto.SwipeRequest.class, com.popclub.forgedriver.proto.SwipeRequest.Builder.class);
    }

    // Construct using com.popclub.forgedriver.proto.SwipeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      direction_ = "";
      x1_ = 0;
      y1_ = 0;
      x2_ = 0;
      y2_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_SwipeRequest_descriptor;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.SwipeRequest getDefaultInstanceForType() {
      return com.popclub.forgedriver.proto.SwipeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.SwipeRequest build() {
      com.popclub.forgedriver.proto.SwipeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.SwipeRequest buildPartial() {
      com.popclub.forgedriver.proto.SwipeRequest result = new com.popclub.forgedriver.proto.SwipeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.popclub.forgedriver.proto.SwipeRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.direction_ = direction_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x1_ = x1_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y1_ = y1_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.x2_ = x2_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.y2_ = y2_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.popclub.forgedriver.proto.SwipeRequest) {
        return mergeFrom((com.popclub.forgedriver.proto.SwipeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.popclub.forgedriver.proto.SwipeRequest other) {
      if (other == com.popclub.forgedriver.proto.SwipeRequest.getDefaultInstance()) return this;
      if (!other.getDirection().isEmpty()) {
        direction_ = other.direction_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getX1() != 0) {
        setX1(other.getX1());
      }
      if (other.getY1() != 0) {
        setY1(other.getY1());
      }
      if (other.getX2() != 0) {
        setX2(other.getX2());
      }
      if (other.getY2() != 0) {
        setY2(other.getY2());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              direction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              x1_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              y1_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              x2_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              y2_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object direction_ = "";
    /**
     * <code>string direction = 1;</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string direction = 1;</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string direction = 1;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      direction_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      direction_ = getDefaultInstance().getDirection();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 1;</code>
     * @param value The bytes for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      direction_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int x1_ ;
    /**
     * <code>int32 x1 = 2;</code>
     * @return The x1.
     */
    @java.lang.Override
    public int getX1() {
      return x1_;
    }
    /**
     * <code>int32 x1 = 2;</code>
     * @param value The x1 to set.
     * @return This builder for chaining.
     */
    public Builder setX1(int value) {

      x1_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearX1() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x1_ = 0;
      onChanged();
      return this;
    }

    private int y1_ ;
    /**
     * <code>int32 y1 = 3;</code>
     * @return The y1.
     */
    @java.lang.Override
    public int getY1() {
      return y1_;
    }
    /**
     * <code>int32 y1 = 3;</code>
     * @param value The y1 to set.
     * @return This builder for chaining.
     */
    public Builder setY1(int value) {

      y1_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y1 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearY1() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y1_ = 0;
      onChanged();
      return this;
    }

    private int x2_ ;
    /**
     * <code>int32 x2 = 4;</code>
     * @return The x2.
     */
    @java.lang.Override
    public int getX2() {
      return x2_;
    }
    /**
     * <code>int32 x2 = 4;</code>
     * @param value The x2 to set.
     * @return This builder for chaining.
     */
    public Builder setX2(int value) {

      x2_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearX2() {
      bitField0_ = (bitField0_ & ~0x00000008);
      x2_ = 0;
      onChanged();
      return this;
    }

    private int y2_ ;
    /**
     * <code>int32 y2 = 5;</code>
     * @return The y2.
     */
    @java.lang.Override
    public int getY2() {
      return y2_;
    }
    /**
     * <code>int32 y2 = 5;</code>
     * @param value The y2 to set.
     * @return This builder for chaining.
     */
    public Builder setY2(int value) {

      y2_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearY2() {
      bitField0_ = (bitField0_ & ~0x00000010);
      y2_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:forgedriver.SwipeRequest)
  }

  // @@protoc_insertion_point(class_scope:forgedriver.SwipeRequest)
  private static final com.popclub.forgedriver.proto.SwipeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.popclub.forgedriver.proto.SwipeRequest();
  }

  public static com.popclub.forgedriver.proto.SwipeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SwipeRequest>
      PARSER = new com.google.protobuf.AbstractParser<SwipeRequest>() {
    @java.lang.Override
    public SwipeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SwipeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SwipeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.popclub.forgedriver.proto.SwipeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

