// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface WaitPresentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.WaitPresentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>int64 timeout_ms = 2;</code>
   * @return The timeoutMs.
   */
  long getTimeoutMs();
}
