// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

public interface WaitPresentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forgedriver.WaitPresentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  boolean getFound();

  /**
   * <code>int32 left = 2;</code>
   * @return The left.
   */
  int getLeft();

  /**
   * <code>int32 top = 3;</code>
   * @return The top.
   */
  int getTop();

  /**
   * <code>int32 right = 4;</code>
   * @return The right.
   */
  int getRight();

  /**
   * <code>int32 bottom = 5;</code>
   * @return The bottom.
   */
  int getBottom();
}
