// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forge_driver.proto

// Protobuf Java Version: 3.25.3
package com.popclub.forgedriver.proto;

/**
 * Protobuf type {@code forgedriver.WaitPresentResponse}
 */
public final class WaitPresentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:forgedriver.WaitPresentResponse)
    WaitPresentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaitPresentResponse.newBuilder() to construct.
  private WaitPresentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaitPresentResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WaitPresentResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_WaitPresentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_WaitPresentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.popclub.forgedriver.proto.WaitPresentResponse.class, com.popclub.forgedriver.proto.WaitPresentResponse.Builder.class);
  }

  public static final int FOUND_FIELD_NUMBER = 1;
  private boolean found_ = false;
  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }

  public static final int LEFT_FIELD_NUMBER = 2;
  private int left_ = 0;
  /**
   * <code>int32 left = 2;</code>
   * @return The left.
   */
  @java.lang.Override
  public int getLeft() {
    return left_;
  }

  public static final int TOP_FIELD_NUMBER = 3;
  private int top_ = 0;
  /**
   * <code>int32 top = 3;</code>
   * @return The top.
   */
  @java.lang.Override
  public int getTop() {
    return top_;
  }

  public static final int RIGHT_FIELD_NUMBER = 4;
  private int right_ = 0;
  /**
   * <code>int32 right = 4;</code>
   * @return The right.
   */
  @java.lang.Override
  public int getRight() {
    return right_;
  }

  public static final int BOTTOM_FIELD_NUMBER = 5;
  private int bottom_ = 0;
  /**
   * <code>int32 bottom = 5;</code>
   * @return The bottom.
   */
  @java.lang.Override
  public int getBottom() {
    return bottom_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (found_ != false) {
      output.writeBool(1, found_);
    }
    if (left_ != 0) {
      output.writeInt32(2, left_);
    }
    if (top_ != 0) {
      output.writeInt32(3, top_);
    }
    if (right_ != 0) {
      output.writeInt32(4, right_);
    }
    if (bottom_ != 0) {
      output.writeInt32(5, bottom_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (found_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, found_);
    }
    if (left_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, left_);
    }
    if (top_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, top_);
    }
    if (right_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, right_);
    }
    if (bottom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, bottom_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.popclub.forgedriver.proto.WaitPresentResponse)) {
      return super.equals(obj);
    }
    com.popclub.forgedriver.proto.WaitPresentResponse other = (com.popclub.forgedriver.proto.WaitPresentResponse) obj;

    if (getFound()
        != other.getFound()) return false;
    if (getLeft()
        != other.getLeft()) return false;
    if (getTop()
        != other.getTop()) return false;
    if (getRight()
        != other.getRight()) return false;
    if (getBottom()
        != other.getBottom()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFound());
    hash = (37 * hash) + LEFT_FIELD_NUMBER;
    hash = (53 * hash) + getLeft();
    hash = (37 * hash) + TOP_FIELD_NUMBER;
    hash = (53 * hash) + getTop();
    hash = (37 * hash) + RIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getRight();
    hash = (37 * hash) + BOTTOM_FIELD_NUMBER;
    hash = (53 * hash) + getBottom();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.popclub.forgedriver.proto.WaitPresentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.popclub.forgedriver.proto.WaitPresentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popclub.forgedriver.proto.WaitPresentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.popclub.forgedriver.proto.WaitPresentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code forgedriver.WaitPresentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:forgedriver.WaitPresentResponse)
      com.popclub.forgedriver.proto.WaitPresentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_WaitPresentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_WaitPresentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.popclub.forgedriver.proto.WaitPresentResponse.class, com.popclub.forgedriver.proto.WaitPresentResponse.Builder.class);
    }

    // Construct using com.popclub.forgedriver.proto.WaitPresentResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      found_ = false;
      left_ = 0;
      top_ = 0;
      right_ = 0;
      bottom_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.popclub.forgedriver.proto.ForgeDriverProto.internal_static_forgedriver_WaitPresentResponse_descriptor;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.WaitPresentResponse getDefaultInstanceForType() {
      return com.popclub.forgedriver.proto.WaitPresentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.WaitPresentResponse build() {
      com.popclub.forgedriver.proto.WaitPresentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.popclub.forgedriver.proto.WaitPresentResponse buildPartial() {
      com.popclub.forgedriver.proto.WaitPresentResponse result = new com.popclub.forgedriver.proto.WaitPresentResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.popclub.forgedriver.proto.WaitPresentResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.found_ = found_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.left_ = left_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.top_ = top_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.right_ = right_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bottom_ = bottom_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.popclub.forgedriver.proto.WaitPresentResponse) {
        return mergeFrom((com.popclub.forgedriver.proto.WaitPresentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.popclub.forgedriver.proto.WaitPresentResponse other) {
      if (other == com.popclub.forgedriver.proto.WaitPresentResponse.getDefaultInstance()) return this;
      if (other.getFound() != false) {
        setFound(other.getFound());
      }
      if (other.getLeft() != 0) {
        setLeft(other.getLeft());
      }
      if (other.getTop() != 0) {
        setTop(other.getTop());
      }
      if (other.getRight() != 0) {
        setRight(other.getRight());
      }
      if (other.getBottom() != 0) {
        setBottom(other.getBottom());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              found_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              left_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              top_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              right_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              bottom_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean found_ ;
    /**
     * <code>bool found = 1;</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return found_;
    }
    /**
     * <code>bool found = 1;</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {

      found_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool found = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      bitField0_ = (bitField0_ & ~0x00000001);
      found_ = false;
      onChanged();
      return this;
    }

    private int left_ ;
    /**
     * <code>int32 left = 2;</code>
     * @return The left.
     */
    @java.lang.Override
    public int getLeft() {
      return left_;
    }
    /**
     * <code>int32 left = 2;</code>
     * @param value The left to set.
     * @return This builder for chaining.
     */
    public Builder setLeft(int value) {

      left_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 left = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeft() {
      bitField0_ = (bitField0_ & ~0x00000002);
      left_ = 0;
      onChanged();
      return this;
    }

    private int top_ ;
    /**
     * <code>int32 top = 3;</code>
     * @return The top.
     */
    @java.lang.Override
    public int getTop() {
      return top_;
    }
    /**
     * <code>int32 top = 3;</code>
     * @param value The top to set.
     * @return This builder for chaining.
     */
    public Builder setTop(int value) {

      top_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 top = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTop() {
      bitField0_ = (bitField0_ & ~0x00000004);
      top_ = 0;
      onChanged();
      return this;
    }

    private int right_ ;
    /**
     * <code>int32 right = 4;</code>
     * @return The right.
     */
    @java.lang.Override
    public int getRight() {
      return right_;
    }
    /**
     * <code>int32 right = 4;</code>
     * @param value The right to set.
     * @return This builder for chaining.
     */
    public Builder setRight(int value) {

      right_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 right = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      right_ = 0;
      onChanged();
      return this;
    }

    private int bottom_ ;
    /**
     * <code>int32 bottom = 5;</code>
     * @return The bottom.
     */
    @java.lang.Override
    public int getBottom() {
      return bottom_;
    }
    /**
     * <code>int32 bottom = 5;</code>
     * @param value The bottom to set.
     * @return This builder for chaining.
     */
    public Builder setBottom(int value) {

      bottom_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bottom = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBottom() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bottom_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:forgedriver.WaitPresentResponse)
  }

  // @@protoc_insertion_point(class_scope:forgedriver.WaitPresentResponse)
  private static final com.popclub.forgedriver.proto.WaitPresentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.popclub.forgedriver.proto.WaitPresentResponse();
  }

  public static com.popclub.forgedriver.proto.WaitPresentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaitPresentResponse>
      PARSER = new com.google.protobuf.AbstractParser<WaitPresentResponse>() {
    @java.lang.Override
    public WaitPresentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WaitPresentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaitPresentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.popclub.forgedriver.proto.WaitPresentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

